global:
  enabled: true

injector:
  enabled: true

  image:
    repository: "hashicorp/vault-k8s"
    tag: "latest"

server:
  dataStorage:
    enabled: true
    size: 20Gi
    mountPath: "/vault/data"
    storageClass: null
    accessMode: ReadWriteOnce
    annotations: {}

  image:
    repository: "hashicorp/vault"
    tag: "1.13.1"

  readinessProbe:
    enabled: true
    exec:
      command:
      - /bin/sh
      - -ec
      - vault status -tks-skip-verify
    failureThreashold: 2
    initDelaySeconds: 5
    periodSeconds: 5
    successThreadhold: 1
    timeoutSeconds: 3

  auditStorage:
    enabled: false

  standalone:
    enabled: false

  extraSecretEnvironmentVars:
    - envName: AWS_ACCESS_KEY_ID
      secretName: eks-cred
      secretKey: AWS_ACCESS_KEY_ID
    - envName: AWS_SECRET_ACCESS_KEY
      secretName: eks-cred
      secretKey: AWS_SECRET_ACCESS_KEY

  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }

        seal "awskms" {
          region = "us-east-1"
          kms_key_id = "7be48e80-31e8-412b-8988-48312b2d8023"
        }

        storage "raft" {
          path = "/vault/file"

          retry_join {
          leader_api_addr = "http://vault-0.vault-internal:8200"
          }

          retry_join {
          leader_api_addr = "http://vault-1.vault-internal:8200"
          }

          retry_join {
          leader_api_addr = "http://vault-2.vault-internal:8200"
          }
        }

        disable_mlock = true
        service_registration "kubernetes" {}

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200


